package com.assigment.Scheduler;

import com.assigment.Scheduler.entity.Student;
import com.assigment.Scheduler.repository.StudentRepository;
import com.assigment.Scheduler.service.StudentImportService;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import static org.assertj.core.api.Assertions.assertThat;

@SpringBootTest
class StudentImportServiceTest {

    @Autowired
    private StudentImportService importService;

    @Autowired
    private StudentRepository studentRepository;

    @Test
    void importsAndUpdatesStudentWithCsvId() {
        studentRepository.deleteAll();
        Student firstImport = student(101L, "Rahul Sharma", 9.2);
        Student savedFirst = importService.saveStudentSafely(firstImport);
        assertThat(savedFirst.getId()).isEqualTo(101L);

        Student update = student(101L, "Rahul Updated", 9.5);
        Student savedUpdate = importService.saveStudentSafely(update);
        assertThat(savedUpdate.getId()).isEqualTo(101L);

        assertThat(studentRepository.count()).isEqualTo(1);
        Student saved = studentRepository.findById(101L).orElseThrow();
        assertThat(saved.getName()).isEqualTo("Rahul Updated");
        assertThat(saved.getCgpa()).isEqualTo(9.5);
    }

    @Autowired
    private com.assigment.Scheduler.controller.StudentController studentController;

    @Test
    void createsStudentWithAutoGeneratedIdWhenIdIsNull() {
        studentRepository.deleteAll();
        Student autoStudent = student(null, "Aarav Gupta", 8.8);
        Student saved = importService.saveStudentSafely(autoStudent);

        assertThat(saved.getId()).isNotNull();
        assertThat(saved.getName()).isEqualTo("Aarav Gupta");
        assertThat(studentRepository.findById(saved.getId())).isPresent();
    }

    @Test
    void deletesStudentSuccessfullyWithoutError() {
        Student autoStudent = student(null, "Rohan Verma", 8.2);
        Student saved = importService.saveStudentSafely(autoStudent);
        org.springframework.http.ResponseEntity<?> resp = studentController.deleteStudent(saved.getId());
        assertThat(resp.getStatusCode().is2xxSuccessful()).isTrue();
        assertThat(studentRepository.findById(saved.getId())).isEmpty();
    }

    private Student student(Long id, String name, double cgpa) {
        Student student = new Student();
        student.setId(id);
        student.setName(name);
        student.setBranch("COMPUTER SCIENCE & ENGINEERING");
        student.setCgpa(cgpa);
        student.setWithdrawn(false);
        return student;
    }
}